title: "Lurninghut"
email: lurninghut@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Gaurav
paginate: 30
disqus: 'gauravbhatt13'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  Gaurav:
    name: Gaurav Bhatt
    display_name: Gaurav
    avatar: 'assets/images/sal.png'
    email: gauravbhatt13@gmail.com
    web: https://lurninghut.com
    twitter: https://twitter.com/gauravbhatt13
    description: "Software Developer"

# Social
social:
  instagram: https://www.instagram.com/gauravbhatt13/
  facebook: https://www.facebook.com/gauravbhatt13
  twitter: https://twitter.com/gauravbhatt13

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives